version: "3"
services:
  db:
    build: ./db/
    restart: always
    env_file: .env
    network_mode: "host"
    expose:
      - "3306"
    volumes:
      - "db:/var/lib/mysql"
      - /etc/localtime:/etc/localtime
    logging:
      driver: "${LOGGING}"
      options:
        max-size: 10m
  radar:
    build: ./radar/
    restart: always
    env_file: .env
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime
    logging:
      driver: "${LOGGING}"
      options:
        max-size: 10m
  pitherm:
    build: ./pitherm/
    restart: always
    env_file: .env
    network_mode: "host"
    volumes:
      - "/sys/bus/w1/:/sys/bus/w1/"
    devices:
      - "/dev/mem:/dev/mem"
    cap_add:
      - SYS_RAWIO
    volumes:
      - /etc/localtime:/etc/localtime
    logging:
      driver: "${LOGGING}"
      options:
        max-size: 10m
  web:
    build: ./web/
    restart: always
    env_file: .env
    network_mode: "host"
    ports:
      - "80:80"
    depends_on:
      - radar
      - pitherm
    volumes:
      - /etc/localtime:/etc/localtime
    logging:
      driver: "${LOGGING}"
      options:
        max-size: 10m
  homebridge:
    build: ./homebridge/
    restart: always
    env_file: .env
    network_mode: "host"
    ports:
      - "51826:51826"
      - "5353:5353"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./homebridge/config.json:/root/.homebridge/config.json
      - ./homebridge/plugins.txt:/root/.homebridge/plugins.txt
    logging:
      driver: "${LOGGING}"
      options:
        max-size: 10m

volumes:
  db:
